// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/auth/signup.proto

package auth

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UsingEmailRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UsingEmailRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UsingEmailRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UsingEmailRequestMultiError, or nil if none found.
func (m *UsingEmailRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UsingEmailRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetEmail()) > 128 {
		err := UsingEmailRequestValidationError{
			field:  "Email",
			reason: "value length must be at most 128 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateEmail(m.GetEmail()); err != nil {
		err = UsingEmailRequestValidationError{
			field:  "Email",
			reason: "value must be a valid email address",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetVerifyCode()) != 6 {
		err := UsingEmailRequestValidationError{
			field:  "VerifyCode",
			reason: "value length must be 6 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_UsingEmailRequest_Username_Pattern.MatchString(m.GetUsername()) {
		err := UsingEmailRequestValidationError{
			field:  "Username",
			reason: "value does not match regex pattern \"^[a-zA-Z][a-zA-Z0-9_]{4,15}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Pwd

	// no validation rules for PwdCfm

	if len(errors) > 0 {
		return UsingEmailRequestMultiError(errors)
	}

	return nil
}

func (m *UsingEmailRequest) _validateHostname(host string) error {
	s := strings.ToLower(strings.TrimSuffix(host, "."))

	if len(host) > 253 {
		return errors.New("hostname cannot exceed 253 characters")
	}

	for _, part := range strings.Split(s, ".") {
		if l := len(part); l == 0 || l > 63 {
			return errors.New("hostname part must be non-empty and cannot exceed 63 characters")
		}

		if part[0] == '-' {
			return errors.New("hostname parts cannot begin with hyphens")
		}

		if part[len(part)-1] == '-' {
			return errors.New("hostname parts cannot end with hyphens")
		}

		for _, r := range part {
			if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
				return fmt.Errorf("hostname parts can only contain alphanumeric characters or hyphens, got %q", string(r))
			}
		}
	}

	return nil
}

func (m *UsingEmailRequest) _validateEmail(addr string) error {
	a, err := mail.ParseAddress(addr)
	if err != nil {
		return err
	}
	addr = a.Address

	if len(addr) > 254 {
		return errors.New("email addresses cannot exceed 254 characters")
	}

	parts := strings.SplitN(addr, "@", 2)

	if len(parts[0]) > 64 {
		return errors.New("email address local phrase cannot exceed 64 characters")
	}

	return m._validateHostname(parts[1])
}

// UsingEmailRequestMultiError is an error wrapping multiple validation errors
// returned by UsingEmailRequest.ValidateAll() if the designated constraints
// aren't met.
type UsingEmailRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UsingEmailRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UsingEmailRequestMultiError) AllErrors() []error { return m }

// UsingEmailRequestValidationError is the validation error returned by
// UsingEmailRequest.Validate if the designated constraints aren't met.
type UsingEmailRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UsingEmailRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UsingEmailRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UsingEmailRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UsingEmailRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UsingEmailRequestValidationError) ErrorName() string {
	return "UsingEmailRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UsingEmailRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUsingEmailRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UsingEmailRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UsingEmailRequestValidationError{}

var _UsingEmailRequest_Username_Pattern = regexp.MustCompile("^[a-zA-Z][a-zA-Z0-9_]{4,15}$")

// Validate checks the field values on UsingEmailReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UsingEmailReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UsingEmailReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UsingEmailReplyMultiError, or nil if none found.
func (m *UsingEmailReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UsingEmailReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAccount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UsingEmailReplyValidationError{
					field:  "Account",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UsingEmailReplyValidationError{
					field:  "Account",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAccount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UsingEmailReplyValidationError{
				field:  "Account",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetToken()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UsingEmailReplyValidationError{
					field:  "Token",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UsingEmailReplyValidationError{
					field:  "Token",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetToken()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UsingEmailReplyValidationError{
				field:  "Token",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UsingEmailReplyMultiError(errors)
	}

	return nil
}

// UsingEmailReplyMultiError is an error wrapping multiple validation errors
// returned by UsingEmailReply.ValidateAll() if the designated constraints
// aren't met.
type UsingEmailReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UsingEmailReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UsingEmailReplyMultiError) AllErrors() []error { return m }

// UsingEmailReplyValidationError is the validation error returned by
// UsingEmailReply.Validate if the designated constraints aren't met.
type UsingEmailReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UsingEmailReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UsingEmailReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UsingEmailReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UsingEmailReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UsingEmailReplyValidationError) ErrorName() string { return "UsingEmailReplyValidationError" }

// Error satisfies the builtin error interface
func (e UsingEmailReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUsingEmailReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UsingEmailReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UsingEmailReplyValidationError{}

// Validate checks the field values on UsingPhoneRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UsingPhoneRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UsingPhoneRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UsingPhoneRequestMultiError, or nil if none found.
func (m *UsingPhoneRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UsingPhoneRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UsingPhoneRequestMultiError(errors)
	}

	return nil
}

// UsingPhoneRequestMultiError is an error wrapping multiple validation errors
// returned by UsingPhoneRequest.ValidateAll() if the designated constraints
// aren't met.
type UsingPhoneRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UsingPhoneRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UsingPhoneRequestMultiError) AllErrors() []error { return m }

// UsingPhoneRequestValidationError is the validation error returned by
// UsingPhoneRequest.Validate if the designated constraints aren't met.
type UsingPhoneRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UsingPhoneRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UsingPhoneRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UsingPhoneRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UsingPhoneRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UsingPhoneRequestValidationError) ErrorName() string {
	return "UsingPhoneRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UsingPhoneRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUsingPhoneRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UsingPhoneRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UsingPhoneRequestValidationError{}

// Validate checks the field values on UsingPhoneReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UsingPhoneReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UsingPhoneReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UsingPhoneReplyMultiError, or nil if none found.
func (m *UsingPhoneReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UsingPhoneReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UsingPhoneReplyMultiError(errors)
	}

	return nil
}

// UsingPhoneReplyMultiError is an error wrapping multiple validation errors
// returned by UsingPhoneReply.ValidateAll() if the designated constraints
// aren't met.
type UsingPhoneReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UsingPhoneReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UsingPhoneReplyMultiError) AllErrors() []error { return m }

// UsingPhoneReplyValidationError is the validation error returned by
// UsingPhoneReply.Validate if the designated constraints aren't met.
type UsingPhoneReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UsingPhoneReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UsingPhoneReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UsingPhoneReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UsingPhoneReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UsingPhoneReplyValidationError) ErrorName() string { return "UsingPhoneReplyValidationError" }

// Error satisfies the builtin error interface
func (e UsingPhoneReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUsingPhoneReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UsingPhoneReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UsingPhoneReplyValidationError{}
